# Generated by Django 4.0.4 on 2022-05-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoalmuerzo',
            options={'verbose_name': 'Tipo de Almuerzo', 'verbose_name_plural': 'Tipos de almuerzo'},
        ),
        migrations.AlterModelTable(
            name='tipoalmuerzo',
            table='TipoAlmuerzo',
        ),
    ]
