# Generated by Django 4.0.4 on 2022-05-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_rename_tipousuario_usuario_profesor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='imagen_alumno',
            field=models.ImageField(blank=True, default='Fotos/static/images/no-img.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='imagen_profesor',
            field=models.ImageField(blank=True, default='Fotos/static/images/no-img.jpg', upload_to='media'),
        ),
    ]
