# Generated by Django 4.0.1 on 2022-05-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_alter_alumno_imagen_alumno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterModelTable(
            name='profesor',
            table='Profesor',
        ),
    ]
