# Generated by Django 4.0.1 on 2022-05-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0004_alter_profesor_options_alter_profesor_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelTable(
            name='alumno',
            table='Alumno',
        ),
    ]
