# Generated by Django 4.0.1 on 2022-05-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0005_alter_alumno_options_alter_alumno_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursoprofesor',
            options={'verbose_name': 'Curso x Profesor'},
        ),
        migrations.AlterModelTable(
            name='cursoprofesor',
            table='CursoProfesor',
        ),
    ]
