# Generated by Django 4.0.1 on 2022-05-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0006_alter_cursoprofesor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursoprofesor',
            options={'verbose_name': 'Curso x Profesor', 'verbose_name_plural': 'Curso x Profesor'},
        ),
    ]
