# Generated by Django 4.0.1 on 2022-05-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0007_alter_cursoprofesor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursoalumno',
            options={'verbose_name': 'Curso x Alumno', 'verbose_name_plural': 'Curso x Alumno'},
        ),
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'verbose_name': 'Suscripción', 'verbose_name_plural': 'Suscripciones'},
        ),
        migrations.AlterModelTable(
            name='cursoalumno',
            table='CursoAlumno',
        ),
        migrations.AlterModelTable(
            name='suscripcion',
            table='Suscripcion',
        ),
    ]
