# Generated by Django 4.0.4 on 2022-05-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0008_alter_cursoalumno_options_alter_suscripcion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
