# Generated by Django 4.0.4 on 2022-05-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0009_alter_usuario_options_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelTable(
            name='curso',
            table='Curso',
        ),
    ]
